[2016-06-23 22:38:14,867] [MainThread] Changed UID: 0 () GID: 0 ().
[2016-06-23 22:38:14,867] [MainThread] Detaching Process.
[2016-06-23 22:43:28,448] [MainThread] Traceback (most recent call last):
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/Handler.py", line 74, in _process
    self.process(metric)
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 51, in process
    self.post()
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 60, in post
    urllib2.urlopen(req)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>

[2016-06-23 22:43:28,451] [MainThread] Traceback (most recent call last):
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/Handler.py", line 98, in _flush
    self.flush()
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 56, in flush
    self.post()
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 60, in post
    urllib2.urlopen(req)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>

[2016-06-23 22:43:58,557] [MainThread] Traceback (most recent call last):
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/Handler.py", line 74, in _process
    self.process(metric)
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 51, in process
    self.post()
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 60, in post
    urllib2.urlopen(req)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

[2016-06-23 22:43:58,593] [MainThread] Traceback (most recent call last):
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/Handler.py", line 98, in _flush
    self.flush()
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 56, in flush
    self.post()
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 60, in post
    urllib2.urlopen(req)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

[2016-06-23 22:44:28,415] [MainThread] Traceback (most recent call last):
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/Handler.py", line 74, in _process
    self.process(metric)
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 51, in process
    self.post()
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 60, in post
    urllib2.urlopen(req)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

[2016-06-23 22:44:28,441] [MainThread] Traceback (most recent call last):
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/Handler.py", line 98, in _flush
    self.flush()
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 56, in flush
    self.post()
  File "/root/test/0618/myflaskproject/lib/python2.7/site-packages/diamond/handler/httpHandler.py", line 60, in post
    urllib2.urlopen(req)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/python2711/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

[2016-06-23 22:48:42,366] [MainThread] Signal Received: 15
[2016-06-23 22:48:42,366] [MainThread] Signal Received: 15
[2016-06-23 22:48:42,371] [MainThread] Signal Received: 15
[2016-06-23 22:48:42,372] [MainThread] Signal Received: 15
[2016-06-23 22:48:42,374] [MainThread] Signal Received: 15
[2016-06-23 23:16:50,832] [MainThread] Changed UID: 0 () GID: 0 ().
[2016-06-23 23:16:50,833] [MainThread] Detaching Process.
[2016-06-23 23:17:07,858] [MainThread] Took too long to run! Killed!
